{% set name = "fs" %}
{% set version = "2.0.15" %}
{% set hash_type = "sha256" %}
{% set hash_value = "64eb88788db11c1ac45fcd24fe7f4d76c6fade86b4c161cadfa4ec27e4fd12e9" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.python.org/packages/49/c9/2653ff6a3fe58c0658fccd08cea9844a05c42b8d8a2d0342eaebd60039c1/fs-2.0.15.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 1
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - setuptools
    - appdirs >=1.4.3,<2
    - pytz
    - six >=1.10.0,<2
    - enum34 >=1.1.6,<2  # [py2k]
    - scandir >=1.5,<2  # [py2k or py34]

test:
  imports:
    - fs
    - fs.opener

about:
  home: https://www.pyfilesystem.org/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Filesystem abstraction layer for Python
  description: "pyfilesystem2 lets you work with diverse filesystems through a common API."
  doc_url: https://docs.pyfilesystem.org/en/v{{ version }}
  dev_url: 'https://github.com/PyFilesystem/pyfilesystem2'

extra:
  recipe-maintainers: 
    - notestaff
    - willmcgugan
    - ReimarBauer
