{% set name = "fs" %}
{% set version = "2.4.11" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc99d476b500f993df8ef697b96dc70928ca2946a455c396a566efe021126767

build:
  number: 3
  noarch: python
  script: pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - appdirs >=1.4.3,<2
    - pytz
    - six >=1.10.0,<2

test:
  imports:
    - fs
    - fs.opener

about:
  home: https://www.pyfilesystem.org/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Filesystem abstraction layer for Python
  description: "pyfilesystem2 lets you work with diverse filesystems through a common API."
  doc_url: https://docs.pyfilesystem.org/en/v{{ version }}
  dev_url: 'https://github.com/PyFilesystem/pyfilesystem2'

extra:
  recipe-maintainers: 
    - notestaff
    - willmcgugan
    - ReimarBauer
