appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ie/eEdXOGMPd/6IUYqjVvXbaGdxFkm25nfsih7CeKzVT8zL4qHC6SpQZde7X/o4VMSsJ1tAom7vNJpAby4Ge0oZFm2/Il7wDiR3Kgw5GVMLGxVQ9OecAvl70KhDHzMLzCdkZqxS87BWyQEY7HV+RlEQHDI8+wFNfjuUa4cQ7vcV9XKPc6TZdeMeFNnLVgxG4HNq3Jh9duZVyxVt6Xkijntta1Peh5MW2TwRFVWg1+ftXZlKDSiVraLnn5Sknm0WTTYFwu5kH2ayW9r7M3sp4mmnIoxMOSHXZ99t+sLD8rrce4sYB7LDsAxpcqHLiTXH5efpWIZJyEpq8NcRE39fowcEWcsLhFLKzFHvW8Xb4w55WJB4FychEXb3pxY8C2qkp848eNkB3p4ezEhBupPhy56tv/J4MtkW3X5ga2hK8qCxoE//228CBTs6A+sRoJpKETy69bbWbJecflYtvcC3vF+URiNWITR+dCYwgUThlPvPr6t3EXNyxvwzr9s/10g7tvh3b8Bk/dFZdkz5EcYbaLgbNDGh8G6oOvWCZUv7ZBQaubMh2Jesw6aGLMGoQ17KbKuEFQIzsCZnzPXtMAUnY3WtiJI2uM2Ss0I95uHyCh0SIWQ64h1R8RcoqgBqSavD0XXXWApr4oVNujiQRVN7ZYO3/X9FYjbbF1KIGh9oJN10=}
