travis:
  secure:
    BINSTAR_TOKEN: ITaB8kSf3t+duB5z1ZS4q80wpkkIUiaTCz6f0NXMA8bWkZCxdQoIQDKtvpMQNDVrh2gdhzzKKFUv2nkc9Q1u8NFylF4L5l6dqOLidWA/3XRdCz9tFz6gtF5LFeULcD0i3hMmCfH0RqBKoS3n/f1nap6g4xZlNjXhSb3fL++lZF0rBH9SRoPHinpoNgcM0ZLVGLMkf9O7okOibFZz8KPIWzRVHb1lBEXgqHZ5Lg/BbML5eF5Llq6ZWLfxTTiS8d2CF1usGr8VHw1/AEKkpt3nsleNrZks9aR5exVm2UhG+3w07TjT1mpd3K6HV5o2VxTdME9E5cmsNoHKAEh0HxDv59dOpLg8U60gGNJq4f66NfBMDgj3BJyi8auP//D2vIkIFWDStZ0JAXAov7J8JgSgSOo/cBR1W9lfi1XCk9NkGwiEFCIEOYqyIMHZGDI9q0gg1eifhmHb2TM5uAAOnjwn5AXdGHUUXgU+/vWJHWfRz3QO0Uyo7OIYFo8nwoWK7+w+wzM6L1Zq1B+0LEwKs4M+RBJSAN8NskLdR/VaBvS/Gj9J3DIIf/M73LYrHAX/J2r2jW2RhqRf3XtxvTavLT2KH8A50QBzzJQAJzIwCvwhXmetC0IZ6uPuxJRswr2q0gpKelrb8kOH7iHsbyHQECv1idS5pPXoDyINW8q7FI1fa+c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
